---
name: Validate

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: home-assistant/actions/hassfest@master
      - uses: hacs/action@21.11.0
        with:
          category: integration
